# Numpy Intro

NumPy arrays are somewhat like native Python lists, except that

- Data *must be homogeneous* (all elements of the same type).  
- These types must be one of the [data types](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) (`dtypes`) provided by NumPy:

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 


There are also dtypes to represent complex numbers, unsigned integers, etc.

On modern machines, the default dtype for arrays is `float64`

First, we can use ``np.array`` to create arrays from Python lists:

## Array Shape

Unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [1]:
# example 1

import numpy as np 

arr = np.array([10.005,20.2555,30.456789,40.009,50.9911112222])

print(arr.dtype)
arr

float64


array([10.005     , 20.2555    , 30.456789  , 40.009     , 50.99111122])

In [37]:
arr.astype('float32')

array([10.005   , 20.2555  , 30.456789, 40.009   , 50.99111 ],
      dtype=float32)

In [3]:
arr.astype('float16')

array([10.01, 20.25, 30.45, 40.  , 51.  ], dtype=float16)

In [4]:
# example 2

my_arr = np.array([[1,2,3],[4,4,5],[6,8,12]])
my_arr

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  8, 12]])

In [5]:
# example 3

my_arr2 = np.array([[2,3,5,5,5],[1,2],[6,5,7]])
my_arr2

C:\Users\Simona\AppData\Local\Temp\ipykernel_5900\1241383518.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  my_arr2 = np.array([[2,3,5,5,5],[1,2],[6,5,7]])


array([list([2, 3, 5, 5, 5]), list([1, 2]), list([6, 5, 7])], dtype=object)

However, if our matrix is not rectangular (each row having the same length), numpy will fallback to holding each as an `object`, which is no better than python's lists.

In [6]:
# example 4

my_arr2 = np.array([[2,3,5,5,5],[1,2],[6,5,7]])
my_arr2

C:\Users\Simona\AppData\Local\Temp\ipykernel_5900\458847379.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  my_arr2 = np.array([[2,3,5,5,5],[1,2],[6,5,7]])


array([list([2, 3, 5, 5, 5]), list([1, 2]), list([6, 5, 7])], dtype=object)

## Array Creation



In [7]:
# example 5
np.zeros((3,2), dtype=int)


array([[0, 0],
       [0, 0],
       [0, 0]])

In [8]:
np.ones((2,3,4), dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

numpy also has `np.arange` which is its analogue to python's `range`:

In [9]:
# example 7

np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

## Random arrays

In [10]:
# example 8
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1

np.random.random((3,3))


array([[0.04113639, 0.95135079, 0.95548879],
       [0.57888519, 0.43970103, 0.079766  ],
       [0.72317498, 0.72419415, 0.64552018]])

In [11]:
# example 9
# Create a 3x3 array of random integers in the interval [0, 10)

np.random.randint(0,10,(3,3))


array([[4, 1, 3],
       [7, 1, 5],
       [7, 7, 3]])

## Advanced Indexing

In [12]:
# example 10
x = np.array([[3,4,2,4],[7,6,8,8],[1,6,7,7]])
x


array([[3, 4, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
x[0][0]

3

In [14]:
x[2,-1]

7

In [15]:
x[2][-1]

7

In [16]:
x[0,0] = 9999
x

array([[9999,    4,    2,    4],
       [   7,    6,    8,    8],
       [   1,    6,    7,    7]])

# Intro to Pandas

`pandas` is designed to make it easier to work with structured data. 

Most of the analyses you might perform will likely involve using tabular data, e.g., from .csv files or relational databases (e.g., SQL) 

If you see a csv file you should be happy!

The `DataFrame` object in `pandas` is "a two-dimensional tabular, column-oriented data structure with both row and column labels."

If you're curious:

>The `pandas` name itself is derived from *panel data*, an econometrics term for multidimensional structured data sets (data where observations are both per time and per individual), and *Python data analysis* itself. After getting introduced, you can consult the full [`pandas` documentation](http://pandas.pydata.org/pandas-docs/stable/).

In [17]:
import pandas as pd

## Series

In [18]:
# example 11

series = pd.Series(np.random.randn(4),name='test')
series


0    1.258770
1   -0.993890
2    0.108402
3   -1.236383
Name: test, dtype: float64

In [19]:
# example 12
series / 100

0    0.012588
1   -0.009939
2    0.001084
3   -0.012364
Name: test, dtype: float64

In [20]:
series // 100

0    0.0
1   -1.0
2    0.0
3   -1.0
Name: test, dtype: float64

In [21]:
# .describe()

series.describe()


count    4.000000
mean    -0.215775
std      1.144040
min     -1.236383
25%     -1.054514
50%     -0.442744
75%      0.395994
max      1.258770
Name: test, dtype: float64

In [22]:
# .index

series.index = ['SpaceX','BTC','GME','Amazon']
series

SpaceX    1.258770
BTC      -0.993890
GME       0.108402
Amazon   -1.236383
Name: test, dtype: float64

## DataFrames

In [23]:
# example 13 (load a csv dataset)

df = pd.read_csv('../data/housing.csv')
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
0       15.3   4.98   24.0  
1       17.8   9.14   21.6  
2       17.8   4.03   34.7  
3       18.7   2.94   33.4  
4       18.7   5.33   36.2  
..       ...    ...    ...  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9  

[506 rows x 13 columns]

In [24]:
# example 14
print(type(df))
df.tail(5)

<class 'pandas.core.frame.DataFrame'>


CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9

We can select particular rows using standard Python array slicing notation.

```
a[start:stop]  # items start through stop-1
a[start:]      # items start through the rest of the array
a[:stop]       # items from the beginning through stop-1
a[:]           # a copy of the whole array
```

In [25]:
# example 15

df[2:5]

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
2  0.02729  0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8   
3  0.03237  0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0     18.7   
4  0.06905  0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0     18.7   

   LSTAT  PRICE  
2   4.03   34.7  
3   2.94   33.4  
4   5.33   36.2

In [26]:
# example 16
df[12:]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
12   0.09378  12.5   7.87   0.0  0.524  5.889  39.0  5.4509  5.0  311.0   
13   0.62976   0.0   8.14   0.0  0.538  5.949  61.8  4.7075  4.0  307.0   
14   0.63796   0.0   8.14   0.0  0.538  6.096  84.5  4.4619  4.0  307.0   
15   0.62739   0.0   8.14   0.0  0.538  5.834  56.5  4.4986  4.0  307.0   
16   1.05393   0.0   8.14   0.0  0.538  5.935  29.3  4.4986  4.0  307.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
12      15.2  15.71   21.7  
13      21.0   8.26   20.4  
14      21.0  10.26   18.2  
15      21.0   8.47   19.9  
16      21.0   6.58   23.1  
..       ...    ...    ...  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9  

[494 rows x 13 columns]

## `.loc` is your best friend

To select rows and columns using a mixture of integers and labels, the `loc` attribute can be used in a similar way

In [27]:
# example 17

df.loc[df.index[2:5], ['CRIM','ZN']]

CRIM   ZN
2  0.02729  0.0
3  0.03237  0.0
4  0.06905  0.0

In [28]:
# example 18

df.loc[df.CRIM >= 10]

CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
367  13.5222  0.0   18.1   0.0  0.631  3.863  100.0  1.5106  24.0  666.0   
373  11.1081  0.0   18.1   0.0  0.668  4.906  100.0  1.1742  24.0  666.0   
374  18.4982  0.0   18.1   0.0  0.668  4.138  100.0  1.1370  24.0  666.0   
375  19.6091  0.0   18.1   0.0  0.671  7.313   97.9  1.3163  24.0  666.0   
376  15.2880  0.0   18.1   0.0  0.671  6.649   93.3  1.3449  24.0  666.0   
378  23.6482  0.0   18.1   0.0  0.671  6.380   96.2  1.3861  24.0  666.0   
379  17.8667  0.0   18.1   0.0  0.671  6.223  100.0  1.3861  24.0  666.0   
380  88.9762  0.0   18.1   0.0  0.671  6.968   91.9  1.4165  24.0  666.0   
381  15.8744  0.0   18.1   0.0  0.671  6.545   99.1  1.5192  24.0  666.0   
384  20.0849  0.0   18.1   0.0  0.700  4.368   91.2  1.4395  24.0  666.0   
385  16.8118  0.0   18.1   0.0  0.700  5.277   98.1  1.4261  24.0  666.0   
386  24.3938  0.0   18.1   0.0  0.700  4.652  100.0  1.4672  24.0  666.0   
387  22.5971  0.0   18.1   0.0  0.700  5.000   89.5  1.5184  24.0  666.0   
388  14.3337  0.0   18.1   0.0  0.700  4.880  100.0  1.5895  24.0  666.0   
392  11.5779  0.0   18.1   0.0  0.700  5.036   97.0  1.7700  24.0  666.0   
394  13.3598  0.0   18.1   0.0  0.693  5.887   94.7  1.7821  24.0  666.0   
398  38.3518  0.0   18.1   0.0  0.693  5.453  100.0  1.4896  24.0  666.0   
400  25.0461  0.0   18.1   0.0  0.693  5.987  100.0  1.5888  24.0  666.0   
401  14.2362  0.0   18.1   0.0  0.693  6.343  100.0  1.5741  24.0  666.0   
403  24.8017  0.0   18.1   0.0  0.693  5.349   96.0  1.7028  24.0  666.0   
404  41.5292  0.0   18.1   0.0  0.693  5.531   85.4  1.6074  24.0  666.0   
405  67.9208  0.0   18.1   0.0  0.693  5.683  100.0  1.4254  24.0  666.0   
406  20.7162  0.0   18.1   0.0  0.659  4.138  100.0  1.1781  24.0  666.0   
407  11.9511  0.0   18.1   0.0  0.659  5.608  100.0  1.2852  24.0  666.0   
409  14.4383  0.0   18.1   0.0  0.597  6.852  100.0  1.4655  24.0  666.0   
410  51.1358  0.0   18.1   0.0  0.597  5.757  100.0  1.4130  24.0  666.0   
411  14.0507  0.0   18.1   0.0  0.597  6.657  100.0  1.5275  24.0  666.0   
412  18.8110  0.0   18.1   0.0  0.597  4.628  100.0  1.5539  24.0  666.0   
413  28.6558  0.0   18.1   0.0  0.597  5.155  100.0  1.5894  24.0  666.0   
414  45.7461  0.0   18.1   0.0  0.693  4.519  100.0  1.6582  24.0  666.0   
415  18.0846  0.0   18.1   0.0  0.679  6.434  100.0  1.8347  24.0  666.0   
416  10.8342  0.0   18.1   0.0  0.679  6.782   90.8  1.8195  24.0  666.0   
417  25.9406  0.0   18.1   0.0  0.679  5.304   89.1  1.6475  24.0  666.0   
418  73.5341  0.0   18.1   0.0  0.679  5.957  100.0  1.8026  24.0  666.0   
419  11.8123  0.0   18.1   0.0  0.718  6.824   76.5  1.7940  24.0  666.0   
420  11.0874  0.0   18.1   0.0  0.718  6.411  100.0  1.8589  24.0  666.0   
422  12.0482  0.0   18.1   0.0  0.614  5.648   87.6  1.9512  24.0  666.0   
425  15.8603  0.0   18.1   0.0  0.679  5.896   95.4  1.9096  24.0  666.0   
426  12.2472  0.0   18.1   0.0  0.584  5.837   59.7  1.9976  24.0  666.0   
427  37.6619  0.0   18.1   0.0  0.679  6.202   78.7  1.8629  24.0  666.0   
431  10.0623  0.0   18.1   0.0  0.584  6.833   94.3  2.0882  24.0  666.0   
434  13.9134  0.0   18.1   0.0  0.713  6.208   95.0  2.2222  24.0  666.0   
435  11.1604  0.0   18.1   0.0  0.740  6.629   94.6  2.1247  24.0  666.0   
436  14.4208  0.0   18.1   0.0  0.740  6.461   93.3  2.0026  24.0  666.0   
437  15.1772  0.0   18.1   0.0  0.740  6.152  100.0  1.9142  24.0  666.0   
438  13.6781  0.0   18.1   0.0  0.740  5.935   87.9  1.8206  24.0  666.0   
440  22.0511  0.0   18.1   0.0  0.740  5.818   92.4  1.8662  24.0  666.0   
444  12.8023  0.0   18.1   0.0  0.740  5.854   96.6  1.8956  24.0  666.0   
445  10.6718  0.0   18.1   0.0  0.740  6.459   94.8  1.9879  24.0  666.0   
468  15.5757  0.0   18.1   0.0  0.580  5.926   71.0  2.9084  24.0  666.0   
469  13.0751  0.0   18.1   0.0  0.580  5.713   56.7  2.8237  24.0  666.0   
477  15.0234  0.0   18.1   0.0  0.614  5.304   97.3  2.1

### Selecting on multiple conditions

The `&` (and), `|` (or), `~` (not) can be used to combine queries:

In [29]:
# example 19

#df.loc[(df.CRIM >= 10) & (df['DIS'] >= 1.5)]



More complex:

In [30]:
# example 20

dd = df.loc[(df.CRIM >= 10) & (df['DIS'] >= 1.5) | (df.RM < 6)]

In [31]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
0       15.3   4.98   24.0  
1       17.8   9.14   21.6  
2       17.8   4.03   34.7  
3       18.7   2.94   33.4  
4       18.7   5.33   36.2  
..       ...    ...    ...  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9  

[506 rows x 13 columns]

In [32]:
# example 21
x = df.iloc[0][5]
x

6.575

Here the index `0, 1,..., 7` is redundant because we can use the country names as an index.

To do this, we set the index to be the `ZN` variable in the dataframe

In [33]:
# example 22

df = pd.read_csv('../data/housing.csv')

df = df.set_index('ZN')
df


CRIM  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
ZN                                                                            
18.0  0.00632   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0     15.3   
0.0   0.02731   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0     17.8   
0.0   0.02729   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8   
0.0   0.03237   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0     18.7   
0.0   0.06905   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0     18.7   
...       ...    ...   ...    ...    ...   ...     ...  ...    ...      ...   
0.0   0.06263  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0     21.0   
0.0   0.04527  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0     21.0   
0.0   0.06076  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0     21.0   
0.0   0.10959  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0     21.0   
0.0   0.04741  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0     21.0   

      LSTAT  PRICE  
ZN                  
18.0   4.98   24.0  
0.0    9.14   21.6  
0.0    4.03   34.7  
0.0    2.94   33.4  
0.0    5.33   36.2  
...     ...    ...  
0.0    9.67   22.4  
0.0    9.08   20.6  
0.0    5.64   23.9  
0.0    6.48   22.0  
0.0    7.88   11.9  

[506 rows x 12 columns]

## We can also do different types of maths

In [34]:
# example 23
df = pd.read_csv('../data/housing.csv')

df['CRIM'] = df.CRIM * 1000
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0      6.32  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     27.31   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2     27.29   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3     32.37   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4     69.05   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..      ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501   62.63   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502   45.27   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503   60.76   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  109.59   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505   47.41   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
0       15.3   4.98   24.0  
1       17.8   9.14   21.6  
2       17.8   4.03   34.7  
3       18.7   2.94   33.4  
4       18.7   5.33   36.2  
..       ...    ...    ...  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9  

[506 rows x 13 columns]

In [35]:
# example 24
df = pd.read_csv('../data/housing.csv')

df_boston = df.copy() #Copies original df 

df_boston['CRIM'] = df_boston['ZN'] * 1e6 / df_boston.CRIM
df_boston
df_boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    2.848101e+09  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.000000e+00   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.000000e+00   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.000000e+00   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.000000e+00   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..            ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.000000e+00   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.000000e+00   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.000000e+00   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.000000e+00   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.000000e+00   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
0       15.3   4.98   24.0  
1       17.8   9.14   21.6  
2       17.8   4.03   34.7  
3       18.7   2.94   33.4  
4       18.7   5.33   36.2  
..       ...    ...    ...  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9  

[506 rows x 13 columns]

In [36]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO  LSTAT  PRICE  
0       15.3   4.98   24.0  
1       17.8   9.14   21.6  
2       17.8   4.03   34.7  
3       18.7   2.94   33.4  
4       18.7   5.33   36.2  
..       ...    ...    ...  
501     21.0   9.67   22.4  
502     21.0   9.08   20.6  
503     21.0   5.64   23.9  
504     21.0   6.48   22.0  
505     21.0   7.88   11.9  

[506 rows x 13 columns]