## Interview Questions

### Exercise 1: Reverse Words in a String

Given a string, you need to reverse the order of characters in each word within a sentence while still preserving whitespace and initial word order.

```
Input: "Let's take LeetCode contest"
Output: "s'teL ekat edoCteeL tsetnoc"
```

In [93]:
# exercise 1
Input = "Let's take LeetCode contest"


def reverse_(string):
    a = string.split(' ')
    b = []
    for i in a:
        x = i[::-1]
        b.append(x)
        b.append(' ')
    b.pop()
    
    Output = ''
    for i in range(len(b)):
        Output += b[i]
    return Output

reverse_(Input)

"s'teL ekat edoCteeL tsetnoc"

### Exercise 2: Length of Last Word

Given a string s consists of some words separated by spaces, return the length of the last word in the string. If the last word does not exist, return 0.

A word is a maximal substring consisting of non-space characters only.

```
Input: s = "Hello World"
Output: 5
```

In [11]:
# exercise 2

s = "Hello World"

def length_(x):
    t = x.split(" ")
    answer = len(t[-1])
    if answer != 0:
        return answer
    else:
        return 0

length_(s)

5

### Exercise 3: Plus One

Given a non-empty array of decimal digits representing a non-negative integer, increment one to the integer.

The digits are stored such that the most significant digit is at the head of the list, and each element in the array contains a single digit.

You may assume the integer does not contain any leading zero, except the number 0 itself.

```
Input: digits = [1,2,3]
Output: [1,2,4]
Explanation: The array represents the integer 123.

Input: digits = [4,3,2,1]
Output: [4,3,2,2]
Explanation: The array represents the integer 4321.

Input: digits = [0]
Output: [1]
```

In [74]:
import numpy as np

In [94]:
q = np.array([1,2,3])
r = np.array([4,3,2,1])
s = np.zeros((1), dtype=int)

In [95]:
# exercise 3
def plus_one(x):
    print(f"Input: {x}")    
    y = x
    y[-1] += 1
    print(f"Output: {y}")

    return y

In [96]:
plus_one(q)

Input: [1 2 3]
Output: [1 2 4]


array([1, 2, 4])

In [97]:
plus_one(r)

Input: [4 3 2 1]
Output: [4 3 2 2]


array([4, 3, 2, 2])

In [98]:
plus_one(s)

Input: [0]
Output: [1]


array([1])

### Exercise 4: Capitalize!

You are asked to ensure that the first and last names of people begin with a capital letter in their passports. For example, alison heck should be capitalised correctly as Alison Heck.

Given a full name, your task is to capitalize the name appropriately.

Input Format

A single line of input containing the full name, .

Constraints

The string consists of alphanumeric characters and spaces.
Note: in a word only the first character is capitalized. Example 12abc when capitalized remains 12abc.

Output Format

Print the capitalized string

```
Sample Input
chris alan

Sample Output
Chris Alan
```

In [90]:
# exercise 4
sample = "chris alan"

def capitalize_(x):
    y = x.split()
    z = []
    Output = ''
    for i in y:
        z.append(i.capitalize())
        z.append(' ')
    z.pop()
    for i in range(len(z)):
        Output += z[i]
    return Output

capitalize_(sample)

'Chris Alan'

### Exercise 5: sWAP cASE

You are given a string and your task is to swap cases. In other words, convert all lowercase letters to uppercase letters and vice versa.

```
Www.HackerRank.com → wWW.hACKERrANK.COM
Pythonist 2 → pYTHONIST 2
```

In [105]:
# exercise 5

def sWAP_cASE(x):
    a = list(x)
    result = ''
    for i in range(len(a)):
        if a[i].upper() == a[i]:
            a[i] = a[i].lower()
        elif a[i].lower() == a[i]:
            a[i] = a[i].upper()
    for i in range(len(a)):
        result += a[i]
    return result
    
sWAP_cASE("Www.HackerRank.com")

'wWW.hACKERrANK.COM'

In [106]:
sWAP_cASE("Pythonist 2")

'pYTHONIST 2'