# Math as a tool

## Warmup

Run the following lines in the cell below:

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

In [2]:
# imports here
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Warmup 1: Write a one line function using set operations to verify that two given sets have NO elements in common. 

```
common_elements({1, 2, 3}, {2}) -> True
common_elements({1, 2, 3}, {'a', 'b', 'c'}) -> False
common_elements({1, 2, 3}, {'a', 1, 'hi!'}) -> True
```

In [3]:
# warmup 1
def common_elements(set1, set2):
    return set1.intersection(set2) != set()

print(common_elements({1, 2, 3}, {2}))
print(common_elements({1, 2, 3}, {'a', 'b', 'c'}))
print(common_elements({1, 2, 3}, {'a', 1, 'hi!'}))

True
False
True


## Exercise 1: Dot Product

Write a function `matrix_multiply(A, B)` using for loops, `+` and `*` that takes in two matrices (can be list of lists, or 2d numpy array) and returns their dot product (matrix multiplication). It should work with column vectors ($k \times 1$ dimensions) and row vectors ($1 \times k$) normally.


```import numpy as np

A = [
    [1,2,3],
    [4,5,6]
]

B = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matrix_multiply(A,B)

RETURNS: 
[[30, 36, 42],
 [66, 81, 96]]

---------example 2-------------
# This is a row vector
A = np.array([
    [1,2,3]
])

# This is a column vector
B = np.array([
    [1],
    [4],
    [7]
])

matrix_multiply(A,B)

RETURNS:
[[30]]

```

Use `np.dot` to test your output

In [19]:
# exercise 1

def matrix_multiply(A,B):
    print(f"A is:\n{A}\n B is:\n{B}")
    C = np.zeros((len(A),len(B[0])), dtype=int)
    if len(A[0]) == len(B):
        for n in range(len(A)):
            for m in range(len(B[0])):
                for o in range(len(B)):
                    C[n][m] += A[n][o] * B[o][m]
    else:
        C = False
    return C

In [20]:
A = np.array([[1,2,3]])
B = np.array([[1],[4],[7]])
print(f"Output: \n{matrix_multiply(A,B)}")
print(f"Solution:\n {np.dot(A,B)}")

C = np.array([[1,2,3],[4,5,6]])
D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Output: \n{matrix_multiply(C,D)}")
print(f"Solution: \n{np.dot(C,D)}")


A is:
[[1 2 3]]
 B is:
[[1]
 [4]
 [7]]
Output: 
[[30]]
Solution:
 [[30]]
A is:
[[1 2 3]
 [4 5 6]]
 B is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Output: 
[[30 36 42]
 [66 81 96]]
Solution: 
[[30 36 42]
 [66 81 96]]


## Exercise 2: Matrix Math torture

**2.1** Give 3 examples of non-invertible square matrices that are non-zero

**2.2** Explain why the identity matrix $I$ is necessarily a square matrix with only $1$'s on the diagonal (hint: use the dot product from Q1)

**2.3** The **trace** is commutative for two matrices so $tr(AB) = tr(BA)$. Give an example where this is false for 3 matrices which can all be multiplied together.

**2.4** Give an example of a $4 \times 4$ idempotent matrix (where $A \cdot A = A^2 = A$)

**2.5** solve the following system of equations for `x`, `y` and `z` using matrices and `numpy.linalg.solve`

$$x 	+ 	y 	+ 	z 	= 	6$$

$$2y 	+ 	5z 	= 	−4$$

$$2x 	+ 	5y 	− 	z 	= 	27$$

In [21]:
# exercise 2.1

A = [[2,-2,4],[0,0,0],[3,3,5]]
# A_inv = np.linalg.inv(A)
# print(A_inv) # Error
print(np.array(A),"\n")

B = [[0,3,5],[0,5,6],[0,30,3]]
# B_inv = np.linalg.inv(B)
# print(B_inv) # Error
print(np.array(B), "\n")

C = [[1,3,5,0],[4,6,2,0],[4,9,3,0],[3,4,2,0]]
# C_inv = np.linalg.inv(C)
# print(C_inv) # Error
print(np.array(C))

[[ 2 -2  4]
 [ 0  0  0]
 [ 3  3  5]] 

[[ 0  3  5]
 [ 0  5  6]
 [ 0 30  3]] 

[[1 3 5 0]
 [4 6 2 0]
 [4 9 3 0]
 [3 4 2 0]]


In [26]:
# exercise 2.2

# If an identity matrix has more rows than columns or more columns than rows, multiplying a matrix with more rows than columns,
# or more columns than rows with its identity matrix would  not be possible, since we can only multiply a matrix that has the
# same number of columns as the number of rows of matrix with which it's being multiplied. Ex: M(2x3)*I(2x3) doesn't work since
# the number of columns of the first matrix (3) is not equal to the number of rows of the (non) identity matrix (2).

A = np.array([[0,3,5],[0,5,6]])
I = np.array([[1,0,0],[0,1,0]])

print(f"Non square matrix: \n {A}\nNon square identity matrix: \n {I}\nDot product (not equal to original matrix): \n {matrix_multiply(A,I)}")

A is:
[[0 3 5]
 [0 5 6]]
 B is:
[[1 0 0]
 [0 1 0]]
Non square matrix: 
 [[0 3 5]
 [0 5 6]]
Non square identity matrix: 
 [[1 0 0]
 [0 1 0]]
Dot product (not equal to original matrix): 
 False


In [55]:
# exercise 2.3

A = np.array([[4,6,2,5],[5,3,8,9],[7,8,5,4],[7,6,9,7]])
B = np.array([[8,4,7,6],[9,5,7,8],[9,8,7,4],[9,7,2,4]])
C = np.array([[9,3,5,7],[7,8,9,6],[2,5,6,8],[3,2,1,4]])
print(f"{A}\n\n{B}\n\n{C}")

[[4 6 2 5]
 [5 3 8 9]
 [7 8 5 4]
 [7 6 9 7]]

[[8 4 7 6]
 [9 5 7 8]
 [9 8 7 4]
 [9 7 2 4]]

[[9 3 5 7]
 [7 8 9 6]
 [2 5 6 8]
 [3 2 1 4]]


In [49]:
# exercise 2.4

A = np.identity(4)
print(A)
print(f"\n {np.dot(A,A)}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [28]:
# exercise 2.5

Matrix = np.array([[1,1,1],[0,2,5],[2,5,-1]])
Solutions = np.array([6,-4,27])
x = np.linalg.solve(Matrix, Solutions)
x

array([ 5.,  3., -2.])

In [29]:
np.allclose(np.dot(Matrix,x),Solutions)

True

## Exercise 3: Linear Algebra

Write each of the following systems of equations as a matrix and solve them using the numpy function from the lecture/pre-lecture.

HINT:

To solve the system for `a`, `b`, and `c`:

$$\begin{bmatrix} 2 & 1 & 2 \\ 1 & 5 & 3 \\ 4 & 1 & 2 \end{bmatrix} \begin{bmatrix} a \\ b \\ c \end{bmatrix} = \begin {bmatrix} 20\\ 38\\ 26 \end{bmatrix} $$

```
Matrix = np.array([[2,1,2], [1,5,3], [4,1,2]])
Solutions = np.array([20, 38, 26])
x = np.linalg.solve(Matrix, Solutions)
x
```

### Exercise 3.1

$$3x + 2y + z = 7$$
$$4x + 5y + 2z = 14$$
$$2x + 4y + 3z = 10$$


In [15]:
# exercise 3.1

Matrix = np.array([[3,2,1],[4,5,2],[2,4,3]])
Solutions = np.array([7,14,10])
x1 = np.linalg.solve(Matrix, Solutions)
x1

array([1., 2., 0.])

In [16]:
np.allclose(np.dot(Matrix,x1),Solutions)

True

### Exercise 3.2

$$3a + 3b + c = 16$$
$$2a + b + 3c = 11$$
$$4a + 2b + 5c = 21$$

In [17]:
# exercise 3.2
Matrix = np.array([[3,3,1],[2,1,3],[4,2,5]])
Solutions = np.array([16,11,21])
x2 = np.linalg.solve(Matrix, Solutions)
x2

array([3., 2., 1.])

In [18]:
np.allclose(np.dot(Matrix,x2),Solutions)

True

### Exercise 3.3

$$4i + 2j + k = 0$$
$$5i + j + 3k = 2$$
$$3i + 3j + 4k = 8$$

In [19]:
# exercise 3.3
Matrix = np.array([[4,2,1],[5,1,3],[3,3,4]])
Solutions = np.array([3,3,4])
x3 = np.linalg.solve(Matrix, Solutions)
x3

array([0.33333333, 0.73333333, 0.2       ])

In [20]:
np.allclose(np.dot(Matrix,x3),Solutions)

True

## Exercise 4: Is it Prime?

A [prime number](https://en.wikipedia.org/wiki/Prime_number) is a number that can only be divided by 1 and by itself. 

Write a function that takes in a positive integer and returns `True` if it's prime and `False` otherwise.

```
check_prime(5) -> True
check_prime(13) -> True
check_prime(9) -> False
check_prime(15) -> False
```

In [21]:
# exercise 4

def check_prime(x):
    result = True
    for i in range(2,x):
        if x % i == 0:
            result = False
    return result

In [22]:
for i in range(1,21):
    print(f"{i} is prime: {check_prime(i)}")

1 is prime: True
2 is prime: True
3 is prime: True
4 is prime: False
5 is prime: True
6 is prime: False
7 is prime: True
8 is prime: False
9 is prime: False
10 is prime: False
11 is prime: True
12 is prime: False
13 is prime: True
14 is prime: False
15 is prime: False
16 is prime: False
17 is prime: True
18 is prime: False
19 is prime: True
20 is prime: False
